site:
  github:
    project_title: Вопросы по RoR
    project_tagline: A GitHub Pages site to showcase repository metadata
    repository_name: RoR Questions
locale: ru_RU     
title: Вопросы по RoR
project_title: Вопросы по RoR
project_tagline: A GitHub Pages site to showcase repository metadata
repository_name: RoR Questions

### Exclude from processing ###
exclude:
  - README.md
